fix: custom fields and validations for section 14
resilient-tech/india-compliance pull request #2125
Opened 2024-05-16 11:07 UTC by priyanshshah2442

2024-05-16 13:09 UTC, ljain112 commented on india_compliance/patches.txt
> +execute:from india_compliance.gst_india.setup import create_custom_fields; create_custom_fields() #50
.

2024-05-17 05:19 UTC, ljain112 commented on india_compliance/gst_india/constants/custom_fields.py
> +            "options": "\nCollect Tax u/s 52\nReverse Charge u/s 9(5)",
Should it be visible on e-Commerce GSTIN ?

2024-05-17 05:20 UTC, ljain112 commented on india_compliance/gst_india/client_scripts/sales_invoice.js
> +                    "Enable Sales through E-commerce Operators in GST Settings to set Supply Liable to {0}",[supply_liable_to]
You can also give link to GST Settings.

2024-05-17 05:21 UTC, ljain112 commented on india_compliance/gst_india/overrides/transaction.py
> +
return if it is not ecommerce sales

2024-05-20 13:32 UTC, ljain112 commented on india_compliance/gst_india/constants/custom_fields.py
> +        },
depends on ecommerce_gstinalso

2024-05-20 13:33 UTC, ljain112 commented on india_compliance/gst_india/doctype/gst_settings/gst_settings.json
> +   "default": "0",
Patch to enable this fields if any sales invoice is with e-Commerce GSTIN

2024-05-20 13:35 UTC, ljain112 commented on india_compliance/gst_india/report/gstr_1/gstr_1.py
> +                Sum(si_item.taxable_value).as_("total_taxable_value"),
Currently we are not using item gst details field in old report

2024-05-20 13:36 UTC, ljain112 commented on india_compliance/gst_india/client_scripts/delivery_note.js
> +    is_reverse_charge(frm) {
I function is repeated multiple times Commonify this function

2024-05-20 13:37 UTC, ljain112 commented on india_compliance/gst_india/client_scripts/sales_invoice.js
> +            frm.set_value("supply_liable_to", "")
Backend logic and hooks for updating field in onload and before_print.(Reger to gst breackup table)

2024-05-21 10:12 UTC, ljain112 commented on india_compliance/gst_india/overrides/transaction.py
> +    if gst_settings.enable_sales_through_ecommerce_operators and doc.ecommerce_gstin:
indentation

2024-05-21 10:17 UTC, ljain112 commented on india_compliance/patches/post_install/set_default_gst_settings.py
> +    for doctype in ["Sales Invoice", "Sales Order", "Delivery Note"]:
Sales Invoice

2024-05-21 10:19 UTC, ljain112 commented on india_compliance/gst_india/doctype/gst_settings/gst_settings.json
> +   "label": "Enable Sales through E-commerce Operators"
Toggle eCommerce gstn field based on settings

2024-05-23 05:50 UTC, ljain112 commented on india_compliance/gst_india/overrides/transaction.py
> +    if doc.doctype in ["Sales Order", "Sales Invoice", "Delivery Note"]:
.

2024-05-23 05:51 UTC, ljain112 commented on india_compliance/gst_india/report/gstr_1/gstr_1.py
> +                Sum(
.

2024-05-23 05:52 UTC, ljain112 commented on india_compliance/gst_india/report/gstr_1/gstr_1.py
> +            .where(Date(si.posting_date) >= getdate(self.filters.from_date))
gstr-1

2024-05-23 05:59 UTC, ljain112 commented on india_compliance/public/js/sales_transaction/sales_transaction.js
> +        frm.set_df_property("supply_liable_to", "hidden", 1);
already field property

2024-05-23 10:31 UTC, ljain112 commented on india_compliance/gst_india/constants/custom_fields.py
> +            "depends_on": "eval:gst_settings.enable_sales_through_ecommerce_operators",
do we need to toggle it from backend ?

2024-05-23 13:19 UTC, vorasmit commented on india_compliance/gst_india/constants/custom_fields.py
> +            "fieldname": "supply_liable_to",
ecommerce_supply_type

2024-05-23 13:24 UTC, vorasmit commented on india_compliance/patches/v14/enable_sales_through_ecommerce_operator.py
> +    if not frappe.db.exists(
reuse

2024-05-23 13:32 UTC, vorasmit commented on india_compliance/gst_india/overrides/transaction.py
> +    set_supply_liable_to(doc)
can be after ignore

2024-05-23 13:35 UTC, vorasmit commented on india_compliance/gst_india/report/gstr_1/gstr_1.py
> +                Case()
.

2024-05-23 13:41 UTC, vorasmit commented on india_compliance/gst_india/report/gstr_1/gstr_1.py
> +            .left_join(si_item)
query re-write.

2024-05-24 10:39 UTC, ljain112 requested changes

2024-05-24 10:39 UTC, ljain112 commented on india_compliance/gst_india/constants/custom_fields.py
> +            "label": "Ecommerce Supply Type",
E-commerce

2024-05-25 07:27 UTC, vorasmit commented on india_compliance/gst_india/report/gstr_1/gstr_1.py
> +                ).as_("total_cess_amount"),
```suggestion
                    Sum(
                        Case()
                        .when(
                            taxes.account_head in [cess_account, cess_non_advol],
                            taxes.tax_amount,
                        )
                        .else_(0)
                    )
                ).as_("total_cess_amount"),
```

2024-05-25 07:32 UTC, vorasmit commented on india_compliance/gst_india/report/gstr_1/gstr_1.py
> +            .where(si.company == self.filters.company)
Subqueries can be with these same conditions. This will reduce the data returned by the subquery.

2024-06-13 11:09 UTC, vorasmit approved these changes, later dismissed

2024-06-13 11:31 UTC, vorasmit approved these changes

2024-06-13 13:43 UTC, merged