fix: reverse_charge field validation if present (POS Invoice exception)
resilient-tech/india-compliance pull request #373
Opened 2022-12-06 14:06 UTC by vorasmit

Closes: #372

2022-12-07 11:00 UTC, sagarvora requested changes
I think there are more instances in the same function that will also require use of `.get`

2022-12-07 11:02 UTC, vorasmit commented
> I think there are more instances in the same function that will also require use of `.get`

Other instance is applicable for purchase. Only this one is applicable for Sales.

2022-12-07 11:05 UTC, sagarvora approved these changes

2022-12-07 11:05 UTC, merged

2022-12-16 08:52 UTC, sagarvora commented
@mergifyio backport version-14