feat: Bill of entry for Import of Goods
resilient-tech/india-compliance pull request #470
Opened 2023-02-02 07:45 UTC by vorasmit

## Summary of changes made

- Bill of Entry (as new doctype) with Accounting Dimensions
- Create accounting dimensions fields if they already exist
- Create a Bill of entry from the Purchase Invoice
- Create Payment Entry (as journal entry) from Bill of entry
- Independent taxes table (for BOE) with its calculations (with item-wise rates).
- Default customs account field in Company
- GSTR 3B report with Import purchases

## Demo

https://user-images.githubusercontent.com/10496564/216298062-25d71cc4-cf22-4643-91ed-0efe9634a611.mp4

Closes: #463

2023-03-10 06:29 UTC, sagarvora requested changes

2023-03-10 06:29 UTC, sagarvora commented on india_compliance/gst_india/setup/__init__.py
> +def delete_accounting_dimension_fields():
put in uninstall.py

2023-03-10 06:29 UTC, sagarvora commented on india_compliance/gst_india/constants/custom_fields.py
> +        {
append instead?

2023-03-10 06:29 UTC, sagarvora commented on india_compliance/gst_india/overrides/purchase_invoice.py
> +    existing_bill_of_entry = frappe.db.get_value(
is this really needed? what happens with links in ERPNext doctypes? if needed, add conditions for docstatus and gst category.

2023-03-10 06:29 UTC, sagarvora commented on india_compliance/gst_india/constants/custom_fields.py
> +    ],
add field for default custom payable account. consider creating these accounts by default for new sites.

2023-03-10 06:29 UTC, sagarvora commented on india_compliance/gst_india/doctype/bill_of_entry_taxes/bill_of_entry_taxes.json
> +   "options": "Company:company:default_currency",
hardcode INR?

2023-03-10 06:29 UTC, sagarvora commented on india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.json
> +   "options": "GST-BOE-.YYYY.-",
```suggestion
   "options": "BOE-.YYYY.-",
```

2023-03-10 06:29 UTC, sagarvora commented on india_compliance/gst_india/doctype/bill_of_entry_taxes/bill_of_entry_taxes.json
> +   "label": "Item Wise Tax Rates"
hidden!

2023-03-10 06:29 UTC, sagarvora commented on india_compliance/gst_india/doctype/bill_of_entry/test_bill_of_entry.py
> +    pass
add test to create BoE.

2023-03-13 12:30 UTC, vorasmit commented on india_compliance/gst_india/overrides/purchase_invoice.py
> +    existing_bill_of_entry = frappe.db.get_value(
Conditions added.

2023-03-23 04:44 UTC, merged

2023-03-23 05:29 UTC, sagarvora commented on india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
> +    def before_submit(self):
This should be "validate".

2023-03-23 05:34 UTC, sagarvora commented on india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
> +            self.set_onload("existing_journal_entry", existing_journal_entry)
[optional]

we aren't really using the values in `existing_journal_entry` or `existing_bill_of_entry`. In such cases, using `frappe.db.exists` coupled with a variable name like `journal_entry_exists` better conveys what we are trying to achieve.

2023-03-23 06:05 UTC, sagarvora commented on india_compliance/gst_india/doctype/bill_of_entry/bill_of_entry.py
> +        controller.on_trash(self)
A better approach:

Adding method as "own":
![Screenshot-2023-03-23-113131](https://user-images.githubusercontent.com/16315650/227117247-d267161c-21c4-4dfa-99ee-1fe5275b72f9.png)

Usage (normal):
![Screenshot-2023-03-23-113148](https://user-images.githubusercontent.com/16315650/227117732-47c5595e-9427-4de9-be2a-3ea439f9a72e.png)

2023-03-23 06:23 UTC, sagarvora reviewed
We can disable the "new"  button in list view by checking "user cannot create" in doctype.