feat: override gl_dict, gstin in journal entry
resilient-tech/india-compliance pull request #748
Opened 2023-06-04 10:29 UTC by vorasmit

depends on: https://github.com/frappe/erpnext/pull/35550

2023-06-22 05:24 UTC, sagarvora requested changes

2023-06-22 05:24 UTC, sagarvora commented on india_compliance/patches/post_install/update_company_gstin.py
> +    doc = frappe.qb.DocType("GL Entry")
write better variable names

2023-06-22 05:24 UTC, sagarvora commented on india_compliance/patches/post_install/update_company_gstin.py
> +            .limit(50000)
double this.

2023-06-22 05:24 UTC, sagarvora commented on india_compliance/patches/post_install/update_company_gstin.py
> +            "company_gstin": ("is", "not set"),
be consistent.

2023-06-22 05:24 UTC, sagarvora commented on india_compliance/patches/post_install/update_company_gstin.py
> +@frappe.whitelist()
should not be whitelisted. you may enqueue.

2023-06-22 05:24 UTC, sagarvora commented on india_compliance/patches/post_install/update_company_gstin.py
> +def toggle_allow_on_submit(allow=True):
only in required voucher types

2023-06-22 05:24 UTC, sagarvora commented on india_compliance/gst_india/client_scripts/journal_entry.js
> +    if (!frm.gst_accounts || frm.company != frm.doc.company) {
!==

2023-06-22 05:24 UTC, sagarvora commented on india_compliance/gst_india/constants/custom_fields.py
> +            "print_hide": 1,
0

2023-07-12 13:07 UTC, merged

2023-07-20 05:49 UTC, precihole commented
Hello,

If we applying GST in expense claim then this issue is arising.

![image](https://github.com/resilient-tech/india-compliance/assets/111174201/aabdd8df-2575-411e-b45d-c6dc12969e77)

2023-07-22 06:21 UTC, precihole commented
@sagarvora i am getting that error in Expense Claim not in Sales invoice.