Added e-way Bill status field
resilient-tech/india-compliance pull request #816
Opened 2023-07-03 13:09 UTC by asu1609

This field will display the status of e-way bill.

2023-07-14 04:44 UTC, sagarvora commented on india_compliance/gst_india/constants/custom_fields.py
> +        "fieldname": "ewaybill_status",
`e_waybill_status`

2023-07-14 04:45 UTC, sagarvora commented on india_compliance/gst_india/constants/custom_fields.py
> +        "label": "e-Way Bill Status",
e-Waybill Status

2023-07-14 04:52 UTC, sagarvora commented on india_compliance/gst_india/constants/custom_fields.py
> +        "default": None,
remove

2023-08-02 07:30 UTC, vorasmit commented
- [ ] Manual generation and cancellation of e-Waybill flow using dialog (handle logs)

2023-08-03 05:48 UTC, vorasmit requested changes

2023-08-03 05:48 UTC, vorasmit commented on india_compliance/gst_india/constants/custom_fields.py
> +        "read_only": 1,
editable. banner to depend on this.

2023-08-03 05:48 UTC, vorasmit commented on india_compliance/gst_india/overrides/sales_invoice.py
> +    if doc.ewaybill:
Only for pending vs Not Applicable

2023-08-03 05:48 UTC, vorasmit commented on india_compliance/gst_india/constants/custom_fields.py
> +        "depends_on": "eval:doc.docstatus === 1",
- allow editing only for pending or not applicable.
- visible: pending or not applicable or e-Waybill is not set

2023-08-03 05:48 UTC, vorasmit commented on india_compliance/hooks.py
> +        "before_update_after_submit": "india_compliance.gst_india.overrides.sales_invoice.set_e_waybill_status",
Not handling manual. Hence not required.

2023-08-03 05:48 UTC, vorasmit commented on india_compliance/patches/post_install/update_e_waybill_status_field.py
> +
perf.

2023-08-03 05:48 UTC, vorasmit commented on india_compliance/patches/post_install/update_e_waybill_status_field.py
> +            | (sales_invoice_item.gst_hsn_code.not_like("99%"))
non-gst

2023-08-03 05:48 UTC, vorasmit commented on india_compliance/patches/post_install/update_e_waybill_status_field.py
> +        e_waybill_enabled = frappe.db.get_single_value(
only for pending

2023-08-03 05:48 UTC, vorasmit commented on india_compliance/gst_india/constants/custom_fields.py
> +        "depends_on": "eval:doc.docstatus == 1 && !doc.ewaybill || in_list(['','Pending', 'Not Applicable'], doc.e_waybill_status)",
readonly depends on

2023-08-03 14:24 UTC, merged